In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
red_wine = pd.read_csv('winequality-red.csv',delimiter=';')
white_wine = pd.read_csv('winequality-white.csv',delimiter=';')

In [3]:
red_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
white_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [5]:
red_wine['type']= 'red'
white_wine['type']='white'

In [6]:
white_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6,white
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6,white
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6,white
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,white
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6,white

In [15]:
combined_wine = pd.concat([red_wine,white_wine],ignore_index=True)

In [16]:
combined_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [17]:
correlation = combined_wine.corr()
most_correlated_param_red = correlation['density'].drop('density').idxmax()
most_correlated_param_white = correlation['density'].drop('density').idxmax()

ValueError: could not convert string to float: 'red'

In [12]:
correlation= wine_data.corr()

In [13]:
print(correlation)

                      fixed acidity  volatile acidity  citric acid  \
fixed acidity              1.000000          0.219008     0.324436
volatile acidity           0.219008          1.000000    -0.377981
citric acid                0.324436         -0.377981     1.000000
residual sugar            -0.111981         -0.196011     0.142451
chlorides                  0.298195          0.377124     0.038998
free sulfur dioxide       -0.282735         -0.352557     0.133126
total sulfur dioxide      -0.329054         -0.414476     0.195242
density                    0.458910          0.271296     0.096154
pH                        -0.252700          0.261454    -0.329808
sulphates                  0.299568          0.225984     0.056197
alcohol                   -0.095452         -0.037640    -0.010493
quality                   -0.076743         -0.265699     0.085532

                      residual sugar  chlorides  free sulfur dioxide  \
fixed acidity              -0.111981   0.298195            -0.282735
volatile acidity           -0.196011   0.377124            -0.352557
citric acid                 0.142451   0.038998             0.133126
residual sugar              1.000000  -0.128940             0.402871
chlorides                  -0.128940   1.000000            -0.195045
free sulfur dioxide         0.402871  -0.195045             1.000000
total sulfur dioxide        0.495482  -0.279630             0.720934
density                     0.552517   0.362615             0.025717
pH                         -0.267320   0.044708            -0.145854
sulphates                  -0.185927   0.395593            -0.188457
alcohol                    -0.359415  -0.256916            -0.179838
quality                    -0.036980  -0.200666             0.055463

                      total sulfur dioxide   density        pH  sulphates  \
fixed acidity                    -0.329054  0.458910 -0.252700   0.299568
volatile acidity                 -0.414476  0.271296  0.261454   0.225984
citric acid                       0.195242  0.096154 -0.329808   0.056197
residual sugar                    0.495482  0.552517 -0.267320  -0.185927
chlorides                        -0.279630  0.362615  0.044708   0.395593
free sulfur dioxide               0.720934  0.025717 -0.145854  -0.188457
total sulfur dioxide              1.000000  0.032395 -0.238413  -0.275727
density                           0.032395  1.000000  0.011686   0.259478
pH                               -0.238413  0.011686  1.000000   0.192123
sulphates                        -0.275727  0.259478  0.192123   1.000000
alcohol                          -0.265740 -0.686745  0.121248  -0.003029
quality                          -0.041385 -0.305858  0.019506   0.038485

                       alcohol   quality
fixed acidity        -0.095452 -0.076743
volatile acidity     -0.037640 -0.265699
citric acid          -0.010493  0.085532
residual sugar       -0.359415 -0.036980
chlorides            -0.256916 -0.200666
free sulfur dioxide  -0.179838  0.055463
total sulfur dioxide -0.265740 -0.041385
density              -0.686745 -0.305858
pH                    0.121248  0.019506
sulphates            -0.003029  0.038485
alcohol               1.000000  0.444319
quality               0.444319  1.000000